### ISSUE TITLE
Compatability with Julia 1.0.x and above

### ISSUE THREAD

**Issue by robertdj** [oxinabox/Pipe.jl#12]
Hi

Thanks for a great package. Do you plan to add support for versions of Julia newer than 1.0.0?

In e.g. Julia 1.0.3 and 1.1.0 I get the following error:

    (v1.0) pkg> add Pipe
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
    Resolving package versions...
    ERROR: Unsatisfiable requirements detected for package Pipe [b98c9c47]:
    Pipe [b98c9c47] log:
    ├─possible versions are: [0.0.1-0.0.3, 1.0.0] or uninstalled
    ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.3, 1.0.0]
    └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

More specifically:

    julia> versioninfo()
    Julia Version 1.0.3
    Commit 099e826241 (2018-12-18 01:34 UTC)
    Platform Info:
    OS: Linux (x86_64-linux-gnu)
    CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    WORD_SIZE: 64
    LIBM: libopenlibm
    LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

**Comment by oxinabox** [comment]
looks like I forgot the tag the new release
https://github.com/JuliaLang/METADATA.jl/pull/21164

**Comment by oxinabox** [comment]
should be fixed now, test and close if so?

**Comment by robertdj** [comment]
It works -- thanks!
