### ISSUE TITLE
Allow broadcasting

### ISSUE THREAD

**Issue by xiaodaigh** [oxinabox/Pipe.jl#14]
For example

```
fn(x) = x^2
@pipe fn |> _(2) # works
```

but

```
@pipe fn |> _.(1:2) 
```
doesn't

**Comment by racinmat** [comment]
Also, using `.|>` does not work, I would very appreciate if it was there.
```julia
@pipe 1:10 .|> _*2
```
is not working, I would expect it to work as
```julia
1:10 .|> x->x*2
```

**Comment by oxinabox** [comment]
Seems reasonable.
Interest in making a PR?

**Comment by racinmat** [comment]
I haven't worked with macros much, but I can try to make a PR.
