### ISSUE TITLE
Feature Request: if no `_` is specified then insert into first argument

### ISSUE THREAD

**Issue by xiaodaigh** [oxinabox/Pipe.jl#18]
Currently

`@pipe a |> f(_, b)` is needed but in other tools like Lazy.jl and R's magrittr which allows the first argument to be the previous one without `_` e.g.

`@pipe a |> f(b)` would be equivalent to `f(a,b)` and `@pipe a |> f(_, b)`

**Comment by oxinabox** [comment]
Not to come across as harsh, but we are not going to do that.
Pipe.jl is explicit.
As you say, other packages like Lazy.jl do it.
I particularly like [Hose.jl](https://github.com/FNj/Hose.jl/) which originated as a fork of Pipe.jl but with that feature added.
You can check the big list of alternatives for others.
https://github.com/JuliaLang/julia/issues/5571#issuecomment-205754539

**Comment by xiaodaigh** [comment]
Not harsh at all. I get it. I will go jump off a cliff now. Jsut joking.

Yeah. I will check out Hose.jl.

Thanks.
