### ISSUE TITLE
Syntax proposal for `begin` and `end` block

### ISSUE THREAD

**Issue by xiaodaigh** [oxinabox/Pipe.jl#19]
Would it be possible to do this

```julia
@pipe something begin
  fn(_)
  fn2(a, _)
  fn3(_, a)
end
```
to be the same as 
```julia
@pipe something |>
  fn(_)  |>
  fn2(a, _)  |>
  fn3(_, a)
```

As `|>` is something inconvenient to type and also the begin and end block makes it easier to add/remove operations.

**Comment by oxinabox** [comment]
I am pretty disinclined to add features to Pipe.jl.
Particularly onces that make it less explict.

It does one thing. It has done that one thing stable-y and without alternatives forms for the last 5 years.
In that time it has had one feature added which was to better support broadcasting.

You might like:
```julia
@pipe(
    something
    |> fn(_)
    |> fn2(a, _)
    |> fn3(_, a)
)
```
which works right now

**Comment by xiaodaigh** [comment]
Ok.
