### ISSUE TITLE
Merging with native pipe

### ISSUE THREAD

**Issue by GitHunter0** [oxinabox/Pipe.jl#26]
Hey @oxinabox , it's a really useful and important package.

The only considerable drawback I see is the necessity to start the chain with `@pipe`.

Therefore, I would hope the native pipe incorporates your package functionalities, have you checked with Julia's core developers team about that possibility? 

Thank you

**Comment by oxinabox** [comment]
yes, there is long issues about this, and long debates about the exact semantics, and if it can actually be added in a way that doesn't suck and also is nonbreaking.

**Comment by oxinabox** [comment]
See https://github.com/JuliaLang/julia/issues/5571#issuecomment-205754539 and other things linked there

**Comment by GitHunter0** [comment]
Hey @oxinabox , thank you for the feedback.

It's sad that Julia's core team is passing the opportunity to combine the best of other languages... R's pipe functionality, both native and with magrittr package, is superb, it is so good for code readability, conciseness and more natural and quicker workflow.
Not allowing a syntax like that will surely reduce the migration of users from R to Julia. It is so disappointing...

Nonetheless, I appreciate your effort to mitigate the issue by creating `Pipe.jl`.

**Comment by oxinabox** [comment]
that isn't what happened at all.
It is an ongoing issue that multiple core devs want,
but that has turned out to be much harder to implement than you might think.

**Comment by GitHunter0** [comment]
I get it, @oxinabox , I thought they kind of have given up the feature, but it seems I misunderstood what happened. I'm glad to be wrong in this case.
