### ISSUE TITLE
Importing Pipe into Main conflicts with an existing identifier

### ISSUE THREAD

**Issue by UserQuestions** [oxinabox/Pipe.jl#5]
I get this error when trying to use pipe in V0.7

**Comment by oxinabox** [comment]
Please post a MWE:

It seems fine to me:

```
bash> julia0.7 -e "using Pipe; @pipe 0.5 |> atan(_, 3)"
```

**Comment by UserQuestions** [comment]
Thanks for the quick response. It appears I was mistaken. I got the error from just `using Pipe`, but the actually functionality seems fine.  Perhaps I double-loaded or made some other mistake.  Thanks!

**Comment by UserQuestions** [comment]
I appear to have spoken too early. My MWE on V0.7.0 is just `using Pipe` that gets the error above.

**Comment by UserQuestions** [comment]
I also get a `WARNING: using Pipe.Pipe in module Main conflicts with an existing identifier.`

I tried running `using Pipe` before anything else when starting Julia and got the same issue.

**Comment by oxinabox** [comment]
I can not reproduce.

**Comment by xiaodaigh** [comment]
Here is an MWE on Windows and Windows WSL Linux

```julia
using PackageCompilerX
create_sysimage(:Pipe, replace_default = true)
```

Restart Julia.

```julia
using Pipe
```

**Comment by oxinabox** [comment]
I feel like this is more likely a PackageCompilerX issue?

**Comment by xiaodaigh** [comment]
This issue with PackageCompiler no longer exists for me

**Comment by xiaodaigh** [comment]
@UserQuestions can this be closed?

**Comment by sijow** [comment]
I can reproduce this problem. It's due to a clash with the `Pipe` datatype exported by Base. It is easy to reproduce by referencing `Pipe` from Base before using Pipe.jl:

```
julia -e "println(typeof(Pipe)); using Pipe; @pipe 0.5 |> atan(_, 3)"
DataType
WARNING: using Pipe.Pipe in module Main conflicts with an existing identifier.
ERROR: importing Pipe into Main conflicts with an existing identifier
```

**Comment by oxinabox** [comment]
Fair enought don't use Pipe before loading Pipe.jl
or do `using Pipe: @pipe`

I guess we should add this to the readme.

**Comment by danjburns** [comment]
Just chiming in. I ran across this issue today with Julia 1.5.2 when launched from VSCode. With a (seemingly) fresh REPL, the first command is `using Pipe` and I get the warning about conflicts with an existing identifier. I say "seemingly" fresh REPL because I don't have visibility into what VSCode does with my configuration when launching the integrated REPL. When I launch Julia from the terminal, I get no such warnings.

If the docs page recommends loading the macro with `using Pipe: @pipe` as suggested above, this would point more folks to a quick workaround.

**Comment by oxinabox** [comment]
Yep this seems to be a Julia 1.5 change, that it occurs in a fresh REPL.
I can reproduce in 1.5 but not in 1.4
anyway i will add to readme

**Comment by sijow** [comment]
In this case wouldn't it be nicer to do `using SimplePipe` (i.e. rename the package)?
