### ISSUE TITLE
Underscore identifier doesn't do indexing replacement

### ISSUE THREAD

**Issue by FNj** [oxinabox/Pipe.jl#7]
When piping DataFrames from DataFrames.jl, one encounters this error very easily:
```julia
@pipe df::DataFrame |> _[:Column]
```
produces: 

>  syntax: all-underscore identifier used as rvalue around In[45]:1

**Comment by oxinabox** [comment]
That is weird, I'll have to have a play.

I suspect it isn't the `DataFrames` but something else, like `getindex` not having the AST expected.

**Comment by FNj** [comment]
You are right, this'll produce the same problem:
```julia
array = Vector(1:10)
@pipe array |> _[4]
```

**Comment by FNj** [comment]
In fact this won't work either:
```julia
array = Vector(1:10)
@pipe "ROFL" |> _
```

**Comment by FNj** [comment]
I've proposed changes needed in a pull request: https://github.com/oxinabox/Pipe.jl/pull/9

**Comment by xiaodaigh** [comment]
Given the PR was merged this can be closed right? @FNj
